src/IOB.WebApp/Controllers/CompromissoController.cs
using AutoMapper;
using IOB.Application.DTO.Response;
using IOB.Domain.Entidades;
using IOB.Domain.Interfaces.Services;
using IOB.Domain.Services;
using IOB.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace IOB.WebApp.Controllers
{
    public class CompromissoController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMapper _mapper;
        private ICompromissoService _compromissoService;

        public CompromissoController(ILogger<HomeController> logger, IMapper mapper, ICompromissoService compromissoService)
        {
            _logger = logger;
            _mapper = mapper;
            _compromissoService = compromissoService;
        }

        public async Task<IActionResult> Index()
        {
            var compromissos = await _compromissoService.ObterTodosAsync();
            var compromissosResponse = _mapper.Map<IEnumerable<CompromissoResponse>>(compromissos);

            return View(compromissosResponse);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string filtro, DateTime? dataCompromisso)
        {
            var compromissos = string.IsNullOrEmpty(filtro) && !dataCompromisso.HasValue
               ? await _compromissoService.ObterTodosAsync()
               : await _compromissoService.ObterPorFiltroAsync(
                    filter: p => p.Titulo.Contains(filtro)
                    || p.Descricao.Contains(filtro)
                    || (dataCompromisso.HasValue && p.DataCompromisso.Date == dataCompromisso.Value.Date));

            var compromissosResponse = _mapper.Map<IEnumerable<CompromissoResponse>>(compromissos);

            return View(compromissosResponse);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CompromissoModel compromissoRequest)
        {
            if (ModelState.IsValid)
            {
                var compromisso = _mapper.Map<Compromisso>(compromissoRequest);
                await _compromissoService.AdicionarAsync(compromisso);

                TempData["ResultOk"] = "Compromisso cadastro!";
                return RedirectToAction("Index");
            }

            return View(compromissoRequest);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var compromisso = await ObterCompromissoAsync(id);
            if (compromisso is null)
                return NotFound();

            return View(compromisso);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarCompromisso(CompromissoModel compromissoRequest)
        {
            if (ModelState.IsValid)
            {
                var compromisso = _mapper.Map<Compromisso>(compromissoRequest);
                await _compromissoService.AtualizarAsync(compromisso);

                TempData["ResultOk"] = "Compromisso Atualizado!";
                return RedirectToAction("Index");
            }

            return View(compromissoRequest);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var compromisso = await ObterCompromissoAsync(id);

            if (compromisso is null)
                return NotFound();

            ViewBag.Desabilitar = true;

            return View(compromisso);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletarCompromisso(int? id)
        {
            var compromisso = await ObterCompromissoAsync(id);
            if (compromisso is null)
                return NotFound();

            await _compromissoService.RemoverPorIdAsync(id.Value);

            TempData["ResultOk"] = "Compromisso Removido!";
            return RedirectToAction("Index");
        }

        private async Task<CompromissoModel> ObterCompromissoAsync(int? id)
        {
            var compromisso = !id.HasValue ? null : await _compromissoService.ObterPorIdAsync(id.Value);
            return _mapper.Map<CompromissoModel>(compromisso);
        }

    }
}

src/IOB.WebApp/Controllers/ContatoController.cs
using AutoMapper;
using IOB.Application.DTO.Response;
using IOB.Application.Interfaces.Services;
using IOB.Domain.Entidades;
using IOB.Domain.Interfaces.Services;
using IOB.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IOB.WebApp.Controllers
{
    public class ContatoController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMapper _mapper;
        private IContatoService _contatoService;
        private ICorreiosService _correiosService;

        public ContatoController(ILogger<HomeController> logger, IContatoService contatoService, ICorreiosService correiosService, IMapper mapper)
        {
            _logger = logger;
            _contatoService = contatoService;
            _correiosService = correiosService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var contatos = await _contatoService.ObterPorFiltroAsync(includeProperties: "Endereco");
            var contatosResponse = _mapper.Map<IEnumerable<ContatoResponse>>(contatos);

            return View(contatosResponse);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string filtro)
        {
            var contatos = string.IsNullOrEmpty(filtro)
                ? await _contatoService.ObterPorFiltroAsync(includeProperties: "Endereco")
                : await _contatoService.ObterPorFiltroAsync(
                    filter: p => p.Nome.Contains(filtro)
                    || p.Email.Contains(filtro)
                    || p.Celular.Contains(filtro)
                    || p.Endereco.Logradouro.Contains(filtro),
                    includeProperties: "Endereco");

            var contatosResponse = _mapper.Map<IEnumerable<ContatoResponse>>(contatos);

            return View(contatosResponse);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Estados = await ObterEstados();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ContatoModel contatoRequest)
        {
            if (ModelState.IsValid)
            {
                var contato = _mapper.Map<Contato>(contatoRequest);
                await _contatoService.AdicionarAsync(contato);

                TempData["ResultOk"] = "Contato cadastro!";
                return RedirectToAction("Index");
            }

            return View(contatoRequest);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var contato = await ObterContatoAsync(id);
            if (contato is null)
                return NotFound();

            ViewBag.Estados = await ObterEstados();
            return View(contato);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarContato(ContatoModel contatoRequest)
        {
            if (ModelState.IsValid)
            {
                var contato = _mapper.Map<Contato>(contatoRequest);
                await _contatoService.AtualizarAsync(contato);

                TempData["ResultOk"] = "Contato Atualizado!";
                return RedirectToAction("Index");
            }

            return View(contatoRequest);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var contato = await ObterContatoAsync(id);

            if (contato is null)
                return NotFound();

            ViewBag.Estados = await ObterEstados();
            return View(contato);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletarContato(int? id)
        {
            var contato = await ObterContatoAsync(id);
            if (contato is null)
                return NotFound();

            await _contatoService.RemoverPorIdAsync(id.Value);

            TempData["ResultOk"] = "Contato Removido!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<JsonResult> ObterEnderecoPorCep(string cep)
        {
            var endereco = await _correiosService.ObterEnderecoPorCepAsync(cep);
            return Json(endereco);
        }

        private async Task<ContatoModel> ObterContatoAsync(int? id)
        {
            var contato = !id.HasValue ? null : await _contatoService.ObterPorFiltroAsync(p => p.Id.Equals(id.Value), includeProperties: "Endereco");

            return _mapper.Map<ContatoModel>(contato?.FirstOrDefault());
        }

        private async Task<ICollection<SelectListItem>?> ObterEstados()
        {
            var estados = await _correiosService.ObterUfAsync();

            return estados?.OrderBy(p => p.Nome).Select(c => new SelectListItem()
            {
                Text = c.Nome,
                Value = c.Sigla
            }).ToList();
        }
    }
}

src/IOB.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IOB Avaliação</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IOB.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Contato" asp-action="Index">IOB Avaliação</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compromisso" asp-action="Index">Compromisso</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IOB Avaliação
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>